/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PresentRouteImport } from './routes/present'
import { Route as OutputRouteImport } from './routes/output'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetSetIdRouteImport } from './routes/set.$setId'
import { Route as SShareIdRouteImport } from './routes/s.$shareId'
import { Route as GTokenRouteImport } from './routes/g.$token'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiShareInviteRouteImport } from './routes/api/share/invite'
import { Route as ApiPublicStatsRouteImport } from './routes/api/public/stats'
import { Route as ApiPublicFeedbackRouteImport } from './routes/api/public/feedback'
import { Route as ApiPublicContributeRouteImport } from './routes/api/public/contribute'
import { Route as ApiMediaUsageRouteImport } from './routes/api/media/usage'
import { Route as ApiMediaUploadRouteImport } from './routes/api/media/upload'
import { Route as ApiGroupsInviteRouteImport } from './routes/api/groups/invite'
import { Route as ApiAuthWelcomeRouteImport } from './routes/api/auth/welcome'
import { Route as ApiAccountDeleteRouteImport } from './routes/api/account/delete'

const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentRoute = PresentRouteImport.update({
  id: '/present',
  path: '/present',
  getParentRoute: () => rootRouteImport,
} as any)
const OutputRoute = OutputRouteImport.update({
  id: '/output',
  path: '/output',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetSetIdRoute = SetSetIdRouteImport.update({
  id: '/set/$setId',
  path: '/set/$setId',
  getParentRoute: () => rootRouteImport,
} as any)
const SShareIdRoute = SShareIdRouteImport.update({
  id: '/s/$shareId',
  path: '/s/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const GTokenRoute = GTokenRouteImport.update({
  id: '/g/$token',
  path: '/g/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareInviteRoute = ApiShareInviteRouteImport.update({
  id: '/api/share/invite',
  path: '/api/share/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStatsRoute = ApiPublicStatsRouteImport.update({
  id: '/api/public/stats',
  path: '/api/public/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedbackRoute = ApiPublicFeedbackRouteImport.update({
  id: '/api/public/feedback',
  path: '/api/public/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContributeRoute = ApiPublicContributeRouteImport.update({
  id: '/api/public/contribute',
  path: '/api/public/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaUsageRoute = ApiMediaUsageRouteImport.update({
  id: '/api/media/usage',
  path: '/api/media/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaUploadRoute = ApiMediaUploadRouteImport.update({
  id: '/api/media/upload',
  path: '/api/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroupsInviteRoute = ApiGroupsInviteRouteImport.update({
  id: '/api/groups/invite',
  path: '/api/groups/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthWelcomeRoute = ApiAuthWelcomeRouteImport.update({
  id: '/api/auth/welcome',
  path: '/api/auth/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountDeleteRoute = ApiAccountDeleteRouteImport.update({
  id: '/api/account/delete',
  path: '/api/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contribute': typeof ContributeRoute
  '/donate': typeof DonateRoute
  '/feedback': typeof FeedbackRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/output': typeof OutputRoute
  '/present': typeof PresentRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/updates': typeof UpdatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/g/$token': typeof GTokenRoute
  '/s/$shareId': typeof SShareIdRoute
  '/set/$setId': typeof SetSetIdRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/auth/welcome': typeof ApiAuthWelcomeRoute
  '/api/groups/invite': typeof ApiGroupsInviteRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/media/usage': typeof ApiMediaUsageRoute
  '/api/public/contribute': typeof ApiPublicContributeRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/api/share/invite': typeof ApiShareInviteRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contribute': typeof ContributeRoute
  '/donate': typeof DonateRoute
  '/feedback': typeof FeedbackRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/output': typeof OutputRoute
  '/present': typeof PresentRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/updates': typeof UpdatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/g/$token': typeof GTokenRoute
  '/s/$shareId': typeof SShareIdRoute
  '/set/$setId': typeof SetSetIdRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/auth/welcome': typeof ApiAuthWelcomeRoute
  '/api/groups/invite': typeof ApiGroupsInviteRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/media/usage': typeof ApiMediaUsageRoute
  '/api/public/contribute': typeof ApiPublicContributeRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/api/share/invite': typeof ApiShareInviteRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contribute': typeof ContributeRoute
  '/donate': typeof DonateRoute
  '/feedback': typeof FeedbackRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/output': typeof OutputRoute
  '/present': typeof PresentRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/updates': typeof UpdatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/g/$token': typeof GTokenRoute
  '/s/$shareId': typeof SShareIdRoute
  '/set/$setId': typeof SetSetIdRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/auth/welcome': typeof ApiAuthWelcomeRoute
  '/api/groups/invite': typeof ApiGroupsInviteRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/media/usage': typeof ApiMediaUsageRoute
  '/api/public/contribute': typeof ApiPublicContributeRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/api/share/invite': typeof ApiShareInviteRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contribute'
    | '/donate'
    | '/feedback'
    | '/legal'
    | '/login'
    | '/output'
    | '/present'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/transparency'
    | '/updates'
    | '/auth/callback'
    | '/g/$token'
    | '/s/$shareId'
    | '/set/$setId'
    | '/api/account/delete'
    | '/api/auth/welcome'
    | '/api/groups/invite'
    | '/api/media/upload'
    | '/api/media/usage'
    | '/api/public/contribute'
    | '/api/public/feedback'
    | '/api/public/stats'
    | '/api/share/invite'
    | '/api/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contribute'
    | '/donate'
    | '/feedback'
    | '/legal'
    | '/login'
    | '/output'
    | '/present'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/transparency'
    | '/updates'
    | '/auth/callback'
    | '/g/$token'
    | '/s/$shareId'
    | '/set/$setId'
    | '/api/account/delete'
    | '/api/auth/welcome'
    | '/api/groups/invite'
    | '/api/media/upload'
    | '/api/media/usage'
    | '/api/public/contribute'
    | '/api/public/feedback'
    | '/api/public/stats'
    | '/api/share/invite'
    | '/api/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contribute'
    | '/donate'
    | '/feedback'
    | '/legal'
    | '/login'
    | '/output'
    | '/present'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/transparency'
    | '/updates'
    | '/auth/callback'
    | '/g/$token'
    | '/s/$shareId'
    | '/set/$setId'
    | '/api/account/delete'
    | '/api/auth/welcome'
    | '/api/groups/invite'
    | '/api/media/upload'
    | '/api/media/usage'
    | '/api/public/contribute'
    | '/api/public/feedback'
    | '/api/public/stats'
    | '/api/share/invite'
    | '/api/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContributeRoute: typeof ContributeRoute
  DonateRoute: typeof DonateRoute
  FeedbackRoute: typeof FeedbackRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  OutputRoute: typeof OutputRoute
  PresentRoute: typeof PresentRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TransparencyRoute: typeof TransparencyRoute
  UpdatesRoute: typeof UpdatesRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  GTokenRoute: typeof GTokenRoute
  SShareIdRoute: typeof SShareIdRoute
  SetSetIdRoute: typeof SetSetIdRoute
  ApiAccountDeleteRoute: typeof ApiAccountDeleteRoute
  ApiAuthWelcomeRoute: typeof ApiAuthWelcomeRoute
  ApiGroupsInviteRoute: typeof ApiGroupsInviteRoute
  ApiMediaUploadRoute: typeof ApiMediaUploadRoute
  ApiMediaUsageRoute: typeof ApiMediaUsageRoute
  ApiPublicContributeRoute: typeof ApiPublicContributeRoute
  ApiPublicFeedbackRoute: typeof ApiPublicFeedbackRoute
  ApiPublicStatsRoute: typeof ApiPublicStatsRoute
  ApiShareInviteRoute: typeof ApiShareInviteRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present': {
      id: '/present'
      path: '/present'
      fullPath: '/present'
      preLoaderRoute: typeof PresentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/output': {
      id: '/output'
      path: '/output'
      fullPath: '/output'
      preLoaderRoute: typeof OutputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set/$setId': {
      id: '/set/$setId'
      path: '/set/$setId'
      fullPath: '/set/$setId'
      preLoaderRoute: typeof SetSetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$shareId': {
      id: '/s/$shareId'
      path: '/s/$shareId'
      fullPath: '/s/$shareId'
      preLoaderRoute: typeof SShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$token': {
      id: '/g/$token'
      path: '/g/$token'
      fullPath: '/g/$token'
      preLoaderRoute: typeof GTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/invite': {
      id: '/api/share/invite'
      path: '/api/share/invite'
      fullPath: '/api/share/invite'
      preLoaderRoute: typeof ApiShareInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stats': {
      id: '/api/public/stats'
      path: '/api/public/stats'
      fullPath: '/api/public/stats'
      preLoaderRoute: typeof ApiPublicStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feedback': {
      id: '/api/public/feedback'
      path: '/api/public/feedback'
      fullPath: '/api/public/feedback'
      preLoaderRoute: typeof ApiPublicFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contribute': {
      id: '/api/public/contribute'
      path: '/api/public/contribute'
      fullPath: '/api/public/contribute'
      preLoaderRoute: typeof ApiPublicContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/usage': {
      id: '/api/media/usage'
      path: '/api/media/usage'
      fullPath: '/api/media/usage'
      preLoaderRoute: typeof ApiMediaUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/upload': {
      id: '/api/media/upload'
      path: '/api/media/upload'
      fullPath: '/api/media/upload'
      preLoaderRoute: typeof ApiMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/groups/invite': {
      id: '/api/groups/invite'
      path: '/api/groups/invite'
      fullPath: '/api/groups/invite'
      preLoaderRoute: typeof ApiGroupsInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/welcome': {
      id: '/api/auth/welcome'
      path: '/api/auth/welcome'
      fullPath: '/api/auth/welcome'
      preLoaderRoute: typeof ApiAuthWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/delete': {
      id: '/api/account/delete'
      path: '/api/account/delete'
      fullPath: '/api/account/delete'
      preLoaderRoute: typeof ApiAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContributeRoute: ContributeRoute,
  DonateRoute: DonateRoute,
  FeedbackRoute: FeedbackRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  OutputRoute: OutputRoute,
  PresentRoute: PresentRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TransparencyRoute: TransparencyRoute,
  UpdatesRoute: UpdatesRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  GTokenRoute: GTokenRoute,
  SShareIdRoute: SShareIdRoute,
  SetSetIdRoute: SetSetIdRoute,
  ApiAccountDeleteRoute: ApiAccountDeleteRoute,
  ApiAuthWelcomeRoute: ApiAuthWelcomeRoute,
  ApiGroupsInviteRoute: ApiGroupsInviteRoute,
  ApiMediaUploadRoute: ApiMediaUploadRoute,
  ApiMediaUsageRoute: ApiMediaUsageRoute,
  ApiPublicContributeRoute: ApiPublicContributeRoute,
  ApiPublicFeedbackRoute: ApiPublicFeedbackRoute,
  ApiPublicStatsRoute: ApiPublicStatsRoute,
  ApiShareInviteRoute: ApiShareInviteRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
