/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresentRouteImport } from './routes/present'
import { Route as OutputRouteImport } from './routes/output'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeckDeckIdRouteImport } from './routes/deck.$deckId'

const PresentRoute = PresentRouteImport.update({
  id: '/present',
  path: '/present',
  getParentRoute: () => rootRouteImport,
} as any)
const OutputRoute = OutputRouteImport.update({
  id: '/output',
  path: '/output',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdRoute = DeckDeckIdRouteImport.update({
  id: '/deck/$deckId',
  path: '/deck/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/output': typeof OutputRoute
  '/present': typeof PresentRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/output': typeof OutputRoute
  '/present': typeof PresentRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/output': typeof OutputRoute
  '/present': typeof PresentRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/output' | '/present' | '/deck/$deckId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/output' | '/present' | '/deck/$deckId'
  id: '__root__' | '/' | '/output' | '/present' | '/deck/$deckId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OutputRoute: typeof OutputRoute
  PresentRoute: typeof PresentRoute
  DeckDeckIdRoute: typeof DeckDeckIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/present': {
      id: '/present'
      path: '/present'
      fullPath: '/present'
      preLoaderRoute: typeof PresentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/output': {
      id: '/output'
      path: '/output'
      fullPath: '/output'
      preLoaderRoute: typeof OutputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId': {
      id: '/deck/$deckId'
      path: '/deck/$deckId'
      fullPath: '/deck/$deckId'
      preLoaderRoute: typeof DeckDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OutputRoute: OutputRoute,
  PresentRoute: PresentRoute,
  DeckDeckIdRoute: DeckDeckIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
