/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PresentRouteImport } from './routes/present'
import { Route as OutputRouteImport } from './routes/output'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetSetIdRouteImport } from './routes/set.$setId'
import { Route as GTokenRouteImport } from './routes/g.$token'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiPublicFeedbackRouteImport } from './routes/api/public/feedback'
import { Route as ApiAuthWelcomeRouteImport } from './routes/api/auth/welcome'

const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentRoute = PresentRouteImport.update({
  id: '/present',
  path: '/present',
  getParentRoute: () => rootRouteImport,
} as any)
const OutputRoute = OutputRouteImport.update({
  id: '/output',
  path: '/output',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetSetIdRoute = SetSetIdRouteImport.update({
  id: '/set/$setId',
  path: '/set/$setId',
  getParentRoute: () => rootRouteImport,
} as any)
const GTokenRoute = GTokenRouteImport.update({
  id: '/g/$token',
  path: '/g/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedbackRoute = ApiPublicFeedbackRouteImport.update({
  id: '/api/public/feedback',
  path: '/api/public/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthWelcomeRoute = ApiAuthWelcomeRouteImport.update({
  id: '/api/auth/welcome',
  path: '/api/auth/welcome',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/feedback': typeof FeedbackRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/output': typeof OutputRoute
  '/present': typeof PresentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/updates': typeof UpdatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/g/$token': typeof GTokenRoute
  '/set/$setId': typeof SetSetIdRoute
  '/api/auth/welcome': typeof ApiAuthWelcomeRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/feedback': typeof FeedbackRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/output': typeof OutputRoute
  '/present': typeof PresentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/updates': typeof UpdatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/g/$token': typeof GTokenRoute
  '/set/$setId': typeof SetSetIdRoute
  '/api/auth/welcome': typeof ApiAuthWelcomeRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/feedback': typeof FeedbackRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/output': typeof OutputRoute
  '/present': typeof PresentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/updates': typeof UpdatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/g/$token': typeof GTokenRoute
  '/set/$setId': typeof SetSetIdRoute
  '/api/auth/welcome': typeof ApiAuthWelcomeRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/donate'
    | '/feedback'
    | '/legal'
    | '/login'
    | '/output'
    | '/present'
    | '/sitemap.xml'
    | '/updates'
    | '/auth/callback'
    | '/g/$token'
    | '/set/$setId'
    | '/api/auth/welcome'
    | '/api/public/feedback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/donate'
    | '/feedback'
    | '/legal'
    | '/login'
    | '/output'
    | '/present'
    | '/sitemap.xml'
    | '/updates'
    | '/auth/callback'
    | '/g/$token'
    | '/set/$setId'
    | '/api/auth/welcome'
    | '/api/public/feedback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/donate'
    | '/feedback'
    | '/legal'
    | '/login'
    | '/output'
    | '/present'
    | '/sitemap.xml'
    | '/updates'
    | '/auth/callback'
    | '/g/$token'
    | '/set/$setId'
    | '/api/auth/welcome'
    | '/api/public/feedback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DonateRoute: typeof DonateRoute
  FeedbackRoute: typeof FeedbackRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  OutputRoute: typeof OutputRoute
  PresentRoute: typeof PresentRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UpdatesRoute: typeof UpdatesRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  GTokenRoute: typeof GTokenRoute
  SetSetIdRoute: typeof SetSetIdRoute
  ApiAuthWelcomeRoute: typeof ApiAuthWelcomeRoute
  ApiPublicFeedbackRoute: typeof ApiPublicFeedbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present': {
      id: '/present'
      path: '/present'
      fullPath: '/present'
      preLoaderRoute: typeof PresentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/output': {
      id: '/output'
      path: '/output'
      fullPath: '/output'
      preLoaderRoute: typeof OutputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set/$setId': {
      id: '/set/$setId'
      path: '/set/$setId'
      fullPath: '/set/$setId'
      preLoaderRoute: typeof SetSetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$token': {
      id: '/g/$token'
      path: '/g/$token'
      fullPath: '/g/$token'
      preLoaderRoute: typeof GTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feedback': {
      id: '/api/public/feedback'
      path: '/api/public/feedback'
      fullPath: '/api/public/feedback'
      preLoaderRoute: typeof ApiPublicFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/welcome': {
      id: '/api/auth/welcome'
      path: '/api/auth/welcome'
      fullPath: '/api/auth/welcome'
      preLoaderRoute: typeof ApiAuthWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DonateRoute: DonateRoute,
  FeedbackRoute: FeedbackRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  OutputRoute: OutputRoute,
  PresentRoute: PresentRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UpdatesRoute: UpdatesRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  GTokenRoute: GTokenRoute,
  SetSetIdRoute: SetSetIdRoute,
  ApiAuthWelcomeRoute: ApiAuthWelcomeRoute,
  ApiPublicFeedbackRoute: ApiPublicFeedbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
